name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          path: main
      - name: Show Working directory
        run: ls
      - name: Setup dsek latex
        uses: actions/checkout@v2
        with:
          repository: Dsek-LTH/dsek-latex
          path: main
      - name: Show Working directory
        run: ls
      - name: Show Working directory
        run: cd main
      - name: Show Working directory
        run: ls
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
              find . -name "main/*.tex" -exec latexmk -pdf -file-line-error -interaction=nonstopmode {} \;
        
      
