name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Setup dsek latex
        uses: actions/checkout@v2
        with:
          repository: Dsek-LTH/dsek-latex
      - name: Show Working directory
        run: ls
      - name: Compile LaTeX documents
        uses: docker://xucheng/texlive-full:latest
        run: |
          find . -name "*.tex" -exec latexmk -pdf -file-line-error -interaction=nonstopmode {} \;
      
