

name: Show directories
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          path: main
      - name: Show Working directory
        run: ls main
      - name: Setup dsek latex
        uses: actions/checkout@v2
        with:
          repository: Dsek-LTH/dsek-latex
          path: main
      - name: Show Working directory
        run: ls main
